### ISSUE TITLE
mode

### ISSUE THREAD

**Issue by DEVOE-YUN** [MediaBrain-SJTU/MemoNet#1]
'intention', 'addressor_warm', 'addressor', 'trajectory'分别代表什么过程

**Comment by WBMao** [comment]
Meaning of different `mode`:

- 'intention': train and test the joint reconstruction model for intention(destination).
- 'addressor_warm': warm up the learnable addressor as mentioned in the supplementary material.
- 'addressor': train and test the learnable addressor using the pseudo label.
- 'trajectory': train and test the trajectory fulfillment encoder-decoder.

**Comment by DEVOE-YUN** [comment]
generate_memory是在哪一步运行的，为什么我训练完intention却并没有得到saved_memory

**Comment by WBMao** [comment]
I'm closing this issue for now. Please feel free to open another issue for other questions :)
