### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by fedebecat** [MediaBrain-SJTU/MemoNet#2]
Hi thanks for sharing your work and acknowledging our MANTRA repository! We are glad you found it useful and that you managed to improve upon it!
I noticed that you shared the dataloader for SDD, are you planning on sharing also the ones for ETH/UCY and NBA with any related code/model?

Thank you very much

Federico

**Comment by WBMao** [comment]
Hi Federico,

Sorry for the late reply.

Currently, we only shared the SDD dataloader. We haven't finished the code cleanup work for ETH/UCY and  NBA datasets yet. But it is expected to be done within the next two months.

As only for the preprocessing code for **ETH/UCY**, you can refer to [Agentformer](https://github.com/Khrylx/AgentFormer). Our preprocessing code is slightly modified from this repository.

**Comment by WBMao** [comment]
Hi @fedebecat ,

We have **updated** the repository. And you can find the code for the ETH/UCY datasets under the `ETH` folder. 

It takes some time to clean the ETH code out.😥 

If you have any further questions about the code, please feel free to contact me.

Weibo Mao

**Comment by fedebecat** [comment]
Great! Thank you very much!

Federico Becattini
