### ISSUE TITLE
Train the intention encoder-decoder and addressor (warm up, finetune) on other dataset

### ISSUE THREAD

**Issue by mpourkeshavarz** [MediaBrain-SJTU/MemoNet#3]
Hi, thanks for sharing your work,
I'm just wondering why you only shared the training part of the trajectory enc-dec on the ETH dataset. So, when training the intention part on the ETH, the data loader doesn't work! 

Thank you

**Comment by WBMao** [comment]
Hi~ @MozhganPourKeshavarz 

The value of `mode` indicates different states of the model training. E.g.,
https://github.com/MediaBrain-SJTU/MemoNet/blob/a9948530d2bb0ce967d4750b0e83da49b9bd4a91/ETH/cfg/eth.yml#L35

And the meaning of different states is explained in [Issue 1](https://github.com/MediaBrain-SJTU/MemoNet/issues/1).

Perhaps, you can post the detailed environments and errors below. This makes it easier for us to determine what is wrong with the code.


Weibo Mao

**Comment by mpourkeshavarz** [comment]
Hi @WBMao , thanks for your prompt reply,
my point is that you are only training the trajectory part of MemoNet for the ETH dataset (and not intention). So when setting mode to 'intention', it's getting the following error:
`  File "Memory-based/nuScenes/models/model_train_trajectory.py", line 104, in __init__
    self.memory_past = torch.load('{}/memory_past.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()
  File "Memory-based/nuScenes/utils/config.py", line 51, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Config' object has no attribute 'memory_path'`

because it's looking for the trained model of the previous parts in `ETH/models/model_train_trajectory.py` line ~104

```
self.memory_past = torch.load('{}/memory_past.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()

self.memory_fut = torch.load('{}/memory_fut.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()

self.memory_dest = torch.load('{}/memory_dest.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()
```

**Comment by WBMao** [comment]
Hi, @MozhganPourKeshavarz 

Sorry for the misunderstanding caused to you. In the ETH's config file, we set the `mode: 'trajectory'` for **DEBUG** only. 

The whole training process should follow the 'intention' ->  'addressor_warm' -> 'addressor' -> 'trajectory'. And strictly, in the 'intention' stage, we do not need to load the memory banks (since it has not been generated yet). We load the memory just for the code's consistency.

As for the error you met, it seems that you change the value of `memory_path` in the config file. Did you comment out this value?

**Comment by mpourkeshavarz** [comment]
Hi @WBMao 
Exactly,
I skipped the 'model_encdec', 'model_encdec_rep', 'memory_path' in the config file to make sure I was **training from scratch** without any pretraining model which caused the mentioned error,
I also tried to set them empty strings and skipped the following lines in ETH/models/model_train_trajectory.py , line ~104 (when want to train 'intention' and set mode in the config file):
```
# self.memory_past = torch.load('{}/memory_past.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()
# self.memory_fut = torch.load('{}/memory_fut.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()
# self.memory_dest = torch.load('{}/memory_dest.pt'.format(cfg.memory_path), map_location=torch.device('cpu')).cuda()
```
```
and now it's getting this error:
Traceback (most recent call last):
  File "/data/development/trajectorypro/Memory-based/ETH/train.py", line 24, in <module>
    main(config)
  File "/data/development/trajectorypro/Memory-based/ETH/train.py", line 19, in main
    t.fit()
  File "/data/development/trajectorypro/Memory-based/ETH/trainer/train_trajectory_AIO.py", line 58, in fit
    loss = self._train_single_epoch()
  File "/data/development/trajectorypro/Memory-based/ETH/trainer/train_trajectory_AIO.py", line 204, in _train_single_epoch
    output, recon = self.MemoNet.reconstruct_trajectory(past_normalized, past_abs, end_pose, fut_normalized[:, -2:, :])
  File "/data/development/trajectorypro/Memory-based/ETH/models/model_train_trajectory.py", line 226, in reconstruct_trajectory
    reconstruction += x_hat
RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 1
```
Are you sure that currently it's possible to train 'intention' , 'addressor_warm', 'addressor' parts in ETH direrctory?

Thank you,
Mozhgan

**Comment by WBMao** [comment]
Hi @MozhganPourKeshavarz 

We are quite sure this code is correct, since it works well in our environment.

For the second error you met, did you change the value of `past_frames` in the config file? The only reason for this error is that the value of `past_frames` is changed from 8 to 4. 

Hope this can help you.

Best regards,
Weibo Mao

**Comment by WBMao** [comment]
I'm closing this issue for now. Please feel free to open another issue for other questions. :)
