### ISSUE TITLE
Generate Memory On Custom Dataset

### ISSUE THREAD

**Issue by zachytong** [MediaBrain-SJTU/MemoNet#7]
It seems that there is no code for memory bank generation. I want to train MemoNet on custom trajectory dataset, is it possible for you to release a version including memory generation? It will be greatly appreciated!

Thanks for your great work!

**Comment by zachytong** [comment]
my bad!  I miss the update info!

**Comment by nchuly** [comment]
same problem, could u please tell me where the memory generation module is? @zachytong
